version: "3.8"
services:
  flask:
    build: .
    container_name: flask
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL= "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 1m30s
  db:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 1m30s
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  